require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PervesController do

  # This should return the minimal set of attributes required to create a valid
  # Perf. As you add validations to Perf, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PervesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all perves as @perves" do
      perf = Perf.create! valid_attributes
      get :index, {}, valid_session
      assigns(:perves).should eq([perf])
    end
  end

  describe "GET show" do
    it "assigns the requested perf as @perf" do
      perf = Perf.create! valid_attributes
      get :show, {:id => perf.to_param}, valid_session
      assigns(:perf).should eq(perf)
    end
  end

  describe "GET new" do
    it "assigns a new perf as @perf" do
      get :new, {}, valid_session
      assigns(:perf).should be_a_new(Perf)
    end
  end

  describe "GET edit" do
    it "assigns the requested perf as @perf" do
      perf = Perf.create! valid_attributes
      get :edit, {:id => perf.to_param}, valid_session
      assigns(:perf).should eq(perf)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Perf" do
        expect {
          post :create, {:perf => valid_attributes}, valid_session
        }.to change(Perf, :count).by(1)
      end

      it "assigns a newly created perf as @perf" do
        post :create, {:perf => valid_attributes}, valid_session
        assigns(:perf).should be_a(Perf)
        assigns(:perf).should be_persisted
      end

      it "redirects to the created perf" do
        post :create, {:perf => valid_attributes}, valid_session
        response.should redirect_to(Perf.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved perf as @perf" do
        # Trigger the behavior that occurs when invalid params are submitted
        Perf.any_instance.stub(:save).and_return(false)
        post :create, {:perf => {}}, valid_session
        assigns(:perf).should be_a_new(Perf)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Perf.any_instance.stub(:save).and_return(false)
        post :create, {:perf => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested perf" do
        perf = Perf.create! valid_attributes
        # Assuming there are no other perves in the database, this
        # specifies that the Perf created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Perf.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => perf.to_param, :perf => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested perf as @perf" do
        perf = Perf.create! valid_attributes
        put :update, {:id => perf.to_param, :perf => valid_attributes}, valid_session
        assigns(:perf).should eq(perf)
      end

      it "redirects to the perf" do
        perf = Perf.create! valid_attributes
        put :update, {:id => perf.to_param, :perf => valid_attributes}, valid_session
        response.should redirect_to(perf)
      end
    end

    describe "with invalid params" do
      it "assigns the perf as @perf" do
        perf = Perf.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Perf.any_instance.stub(:save).and_return(false)
        put :update, {:id => perf.to_param, :perf => {}}, valid_session
        assigns(:perf).should eq(perf)
      end

      it "re-renders the 'edit' template" do
        perf = Perf.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Perf.any_instance.stub(:save).and_return(false)
        put :update, {:id => perf.to_param, :perf => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested perf" do
      perf = Perf.create! valid_attributes
      expect {
        delete :destroy, {:id => perf.to_param}, valid_session
      }.to change(Perf, :count).by(-1)
    end

    it "redirects to the perves list" do
      perf = Perf.create! valid_attributes
      delete :destroy, {:id => perf.to_param}, valid_session
      response.should redirect_to(perves_url)
    end
  end

end
